
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action bnAction;

	private global::Gtk.Action mAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.Table table2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.Entry txtIp;

	private global::Gtk.Entry txtPort;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label label5;

	private global::Gtk.HBox hbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView tvConnections;

	private global::Gtk.VButtonBox vbuttonbox1;

	private global::Gtk.Button btnDisconnect;

	private global::Gtk.Button btnMessage;

	private global::Gtk.Label label6;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView txtLog;

	private global::Gtk.Label label1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.NodeView tvDrinks;

	private global::Gtk.VButtonBox vbuttonbox2;

	private global::Gtk.Button btnNewDrink;

	private global::Gtk.Button btnDeleteDrink;

	private global::Gtk.Label label2;

	private global::Gtk.HButtonBox hbuttonbox1;

	private global::Gtk.Button btnCancel;

	private global::Gtk.Button btnOk;

	private global::Gtk.Label lblState;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.bnAction = new global::Gtk.Action ("bnAction", global::Mono.Unix.Catalog.GetString ("bn"), null, null);
		this.bnAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("bn");
		w1.Add (this.bnAction, null);
		this.mAction = new global::Gtk.Action ("mAction", global::Mono.Unix.Catalog.GetString ("m"), null, null);
		this.mAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("m");
		w1.Add (this.mAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Server Settings");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 3;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		this.table2.BorderWidth = ((uint)(2));
		// Container child table2.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("IP");
		this.table2.Add (this.label3);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.label3]));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Port");
		this.table2.Add (this.label4);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2[this.label4]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.txtIp = new global::Gtk.Entry ();
		this.txtIp.CanFocus = true;
		this.txtIp.Name = "txtIp";
		this.txtIp.IsEditable = false;
		this.txtIp.HasFrame = false;
		this.txtIp.InvisibleChar = '●';
		this.table2.Add (this.txtIp);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2[this.txtIp]));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.txtPort = new global::Gtk.Entry ();
		this.txtPort.CanFocus = true;
		this.txtPort.Name = "txtPort";
		this.txtPort.Text = global::Mono.Unix.Catalog.GetString ("2048");
		this.txtPort.IsEditable = true;
		this.txtPort.InvisibleChar = '●';
		this.table2.Add (this.txtPort);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2[this.txtPort]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		this.table2.Add (this.vbox2);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2[this.vbox2]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		this.notebook1.Add (this.table2);
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
		this.notebook1.SetTabLabel (this.table2, this.label5);
		this.label5.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvConnections = new global::Gtk.TreeView ();
		this.tvConnections.CanFocus = true;
		this.tvConnections.Name = "tvConnections";
		this.GtkScrolledWindow.Add (this.tvConnections);
		this.hbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w9.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox ();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.Spacing = 3;
		this.vbuttonbox1.BorderWidth = ((uint)(4));
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnDisconnect = new global::Gtk.Button ();
		this.btnDisconnect.Sensitive = false;
		this.btnDisconnect.CanFocus = true;
		this.btnDisconnect.Name = "btnDisconnect";
		this.btnDisconnect.UseUnderline = true;
		this.btnDisconnect.Label = global::Mono.Unix.Catalog.GetString ("Disconnect");
		this.vbuttonbox1.Add (this.btnDisconnect);
		global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnDisconnect]));
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnMessage = new global::Gtk.Button ();
		this.btnMessage.CanFocus = true;
		this.btnMessage.Name = "btnMessage";
		this.btnMessage.UseUnderline = true;
		this.btnMessage.Label = global::Mono.Unix.Catalog.GetString ("Message");
		this.vbuttonbox1.Add (this.btnMessage);
		global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnMessage]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.hbox1.Add (this.vbuttonbox1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbuttonbox1]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		this.notebook1.Add (this.hbox1);
		global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox1]));
		w13.Position = 1;
		// Notebook tab
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Connections");
		this.notebook1.SetTabLabel (this.hbox1, this.label6);
		this.label6.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txtLog = new global::Gtk.TextView ();
		this.txtLog.CanFocus = true;
		this.txtLog.Name = "txtLog";
		this.GtkScrolledWindow1.Add (this.txtLog);
		this.notebook1.Add (this.GtkScrolledWindow1);
		global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.GtkScrolledWindow1]));
		w15.Position = 2;
		// Notebook tab
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Log");
		this.notebook1.SetTabLabel (this.GtkScrolledWindow1, this.label1);
		this.label1.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.tvDrinks = new global::Gtk.NodeView ();
		this.tvDrinks.CanFocus = true;
		this.tvDrinks.Name = "tvDrinks";
		this.GtkScrolledWindow3.Add (this.tvDrinks);
		this.hbox2.Add (this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow3]));
		w17.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbuttonbox2 = new global::Gtk.VButtonBox ();
		this.vbuttonbox2.Name = "vbuttonbox2";
		this.vbuttonbox2.Spacing = 3;
		this.vbuttonbox2.BorderWidth = ((uint)(4));
		this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.btnNewDrink = new global::Gtk.Button ();
		this.btnNewDrink.CanFocus = true;
		this.btnNewDrink.Name = "btnNewDrink";
		this.btnNewDrink.UseUnderline = true;
		this.btnNewDrink.Label = global::Mono.Unix.Catalog.GetString ("New Drink");
		this.vbuttonbox2.Add (this.btnNewDrink);
		global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.btnNewDrink]));
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.btnDeleteDrink = new global::Gtk.Button ();
		this.btnDeleteDrink.CanFocus = true;
		this.btnDeleteDrink.Name = "btnDeleteDrink";
		this.btnDeleteDrink.UseUnderline = true;
		this.btnDeleteDrink.Label = global::Mono.Unix.Catalog.GetString ("Delete Drink");
		this.vbuttonbox2.Add (this.btnDeleteDrink);
		global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.btnDeleteDrink]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox2.Add (this.vbuttonbox2);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbuttonbox2]));
		w20.Position = 1;
		w20.Expand = false;
		w20.Fill = false;
		this.notebook1.Add (this.hbox2);
		global::Gtk.Notebook.NotebookChild w21 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox2]));
		w21.Position = 3;
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Stats");
		this.notebook1.SetTabLabel (this.hbox2, this.label2);
		this.label2.ShowAll ();
		this.vbox1.Add (this.notebook1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
		w22.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox ();
		this.hbuttonbox1.Name = "hbuttonbox1";
		this.hbuttonbox1.Spacing = 3;
		this.hbuttonbox1.BorderWidth = ((uint)(4));
		this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnCancel = new global::Gtk.Button ();
		this.btnCancel.Sensitive = false;
		this.btnCancel.CanFocus = true;
		this.btnCancel.Name = "btnCancel";
		this.btnCancel.UseUnderline = true;
		this.btnCancel.Label = global::Mono.Unix.Catalog.GetString ("Stop server");
		this.hbuttonbox1.Add (this.btnCancel);
		global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnCancel]));
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnOk = new global::Gtk.Button ();
		this.btnOk.CanFocus = true;
		this.btnOk.Name = "btnOk";
		this.btnOk.UseUnderline = true;
		this.btnOk.Label = global::Mono.Unix.Catalog.GetString ("Start server");
		this.hbuttonbox1.Add (this.btnOk);
		global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnOk]));
		w24.Position = 1;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox1.Add (this.hbuttonbox1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
		w25.Position = 1;
		w25.Expand = false;
		w25.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lblState = new global::Gtk.Label ();
		this.lblState.Name = "lblState";
		this.lblState.LabelProp = global::Mono.Unix.Catalog.GetString ("Server not running...");
		this.vbox1.Add (this.lblState);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblState]));
		w26.Position = 2;
		w26.Expand = false;
		w26.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 453;
		this.DefaultHeight = 311;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnDisconnect.Clicked += new global::System.EventHandler (this.OnBtnDisconnectClicked);
		this.btnMessage.Clicked += new global::System.EventHandler (this.OnBtnMessageClicked);
		this.btnNewDrink.Clicked += new global::System.EventHandler (this.OnBtnNewDrinkClicked);
		this.btnCancel.Clicked += new global::System.EventHandler (this.OnBtnCancelClicked);
		this.btnOk.Clicked += new global::System.EventHandler (this.OnBtnOkClicked);
	}
}
