
// This file has been generated by the GUI designer. Do not modify.
namespace getraenkeboerse_widgetlibrary
{
	public partial class drinkorderer
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Label lblPrice;

		private global::Gtk.Label lblName;

		private global::Gtk.Button btnBuy;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget getraenkeboerse_widgetlibrary.drinkorderer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "getraenkeboerse_widgetlibrary.drinkorderer";
			// Container child getraenkeboerse_widgetlibrary.drinkorderer.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 10;
			this.vbox1.BorderWidth = ((uint)(3));
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblPrice = new global::Gtk.Label ();
			this.lblPrice.Name = "lblPrice";
			this.lblPrice.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
			this.vbox1.Add (this.lblPrice);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblPrice]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblName = new global::Gtk.Label ();
			this.lblName.Name = "lblName";
			this.lblName.LabelProp = global::Mono.Unix.Catalog.GetString ("drink name");
			this.vbox1.Add (this.lblName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblName]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnBuy = new global::Gtk.Button ();
			this.btnBuy.CanFocus = true;
			this.btnBuy.Name = "btnBuy";
			this.btnBuy.UseUnderline = true;
			// Container child btnBuy.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-index", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("Buy!");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.btnBuy.Add (w3);
			this.vbox1.Add (this.btnBuy);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.btnBuy]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnBuy.Clicked += new global::System.EventHandler (this.OnBtnBuyClicked);
		}
	}
}
