
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Expander expander3;

	private global::Gtk.Table table1;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Entry txtIp;

	private global::Gtk.Entry txtName;

	private global::Gtk.Entry txtPort;

	private global::Gtk.VButtonBox vbuttonbox1;

	private global::Gtk.Button btnConnect;

	private global::Gtk.Button btnDisconnect;

	private global::Gtk.Button btnMsg;

	private global::Gtk.Label GtkLabel3;

	private global::Gtk.VBox vbox3;

	private global::Gtk.Table tblDrinkOrderers;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView tvOrders;

	private global::Gtk.Button btnOrder;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Kasse");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.expander3 = new global::Gtk.Expander (null);
		this.expander3.CanFocus = true;
		this.expander3.Name = "expander3";
		this.expander3.Expanded = true;
		// Container child expander3.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("IP");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
		w1.TopAttach = ((uint)(1));
		w1.BottomAttach = ((uint)(2));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Port");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
		this.table1.Add (this.label3);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtIp = new global::Gtk.Entry ();
		this.txtIp.CanFocus = true;
		this.txtIp.Name = "txtIp";
		this.txtIp.Text = global::Mono.Unix.Catalog.GetString ("127.0.0.1");
		this.txtIp.IsEditable = true;
		this.txtIp.InvisibleChar = '●';
		this.table1.Add (this.txtIp);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.txtIp]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtName = new global::Gtk.Entry ();
		this.txtName.CanFocus = true;
		this.txtName.Name = "txtName";
		this.txtName.Text = global::Mono.Unix.Catalog.GetString ("Zweite Kasse");
		this.txtName.IsEditable = true;
		this.txtName.InvisibleChar = '●';
		this.table1.Add (this.txtName);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.txtName]));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.txtPort = new global::Gtk.Entry ();
		this.txtPort.CanFocus = true;
		this.txtPort.Name = "txtPort";
		this.txtPort.Text = global::Mono.Unix.Catalog.GetString ("2048");
		this.txtPort.IsEditable = true;
		this.txtPort.InvisibleChar = '●';
		this.table1.Add (this.txtPort);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.txtPort]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox ();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnConnect = new global::Gtk.Button ();
		this.btnConnect.CanFocus = true;
		this.btnConnect.Name = "btnConnect";
		this.btnConnect.UseUnderline = true;
		this.btnConnect.Label = global::Mono.Unix.Catalog.GetString ("Connect");
		this.vbuttonbox1.Add (this.btnConnect);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnConnect]));
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnDisconnect = new global::Gtk.Button ();
		this.btnDisconnect.Sensitive = false;
		this.btnDisconnect.CanFocus = true;
		this.btnDisconnect.Name = "btnDisconnect";
		this.btnDisconnect.UseUnderline = true;
		this.btnDisconnect.Label = global::Mono.Unix.Catalog.GetString ("Disconnect");
		this.vbuttonbox1.Add (this.btnDisconnect);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnDisconnect]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.btnMsg = new global::Gtk.Button ();
		this.btnMsg.Sensitive = false;
		this.btnMsg.CanFocus = true;
		this.btnMsg.Name = "btnMsg";
		this.btnMsg.UseUnderline = true;
		this.btnMsg.Label = global::Mono.Unix.Catalog.GetString ("Message!");
		this.vbuttonbox1.Add (this.btnMsg);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.btnMsg]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.table1.Add (this.vbuttonbox1);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.vbuttonbox1]));
		w10.BottomAttach = ((uint)(3));
		w10.LeftAttach = ((uint)(2));
		w10.RightAttach = ((uint)(3));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		this.expander3.Add (this.table1);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("Settings");
		this.GtkLabel3.UseUnderline = true;
		this.expander3.LabelWidget = this.GtkLabel3;
		this.vbox2.Add (this.expander3);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.expander3]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.tblDrinkOrderers = new global::Gtk.Table (((uint)(1)), ((uint)(5)), false);
		this.tblDrinkOrderers.Name = "tblDrinkOrderers";
		this.tblDrinkOrderers.RowSpacing = ((uint)(6));
		this.tblDrinkOrderers.ColumnSpacing = ((uint)(6));
		this.vbox3.Add (this.tblDrinkOrderers);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.tblDrinkOrderers]));
		w13.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.tvOrders = new global::Gtk.NodeView ();
		this.tvOrders.CanFocus = true;
		this.tvOrders.Name = "tvOrders";
		this.GtkScrolledWindow.Add (this.tvOrders);
		this.vbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
		w15.Position = 1;
		// Container child vbox3.Gtk.Box+BoxChild
		this.btnOrder = new global::Gtk.Button ();
		this.btnOrder.CanFocus = true;
		this.btnOrder.Name = "btnOrder";
		this.btnOrder.UseUnderline = true;
		// Container child btnOrder.Gtk.Container+ContainerChild
		global::Gtk.Alignment w16 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w17 = new global::Gtk.HBox ();
		w17.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w18 = new global::Gtk.Image ();
		w18.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
		w17.Add (w18);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w20 = new global::Gtk.Label ();
		w20.LabelProp = global::Mono.Unix.Catalog.GetString ("Rechnung über %%% abschicken");
		w20.UseUnderline = true;
		w17.Add (w20);
		w16.Add (w17);
		this.btnOrder.Add (w16);
		this.vbox3.Add (this.btnOrder);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.btnOrder]));
		w24.Position = 2;
		w24.Expand = false;
		w24.Fill = false;
		this.vbox2.Add (this.vbox3);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
		w25.Position = 1;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 304;
		this.DefaultHeight = 405;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
		this.btnConnect.Clicked += new global::System.EventHandler (this.OnBtnConnectClicked);
		this.btnDisconnect.Clicked += new global::System.EventHandler (this.OnBtnDisconnectClicked);
		this.btnMsg.Clicked += new global::System.EventHandler (this.OnBtnMsgClicked);
		this.btnOrder.Clicked += new global::System.EventHandler (this.OnBtnOrderClicked);
	}
}
